markdown: rdiscount
permalink: /:title/
baseUrl: /blog
url: http://bigbanana.github.com/blog
name: web
author: skxtay
qq: 564493634
email: skxtay@gmail.com
duoshuo: skxtay
github: bigbanana
pygments: true
safe: true
paginate: 20
about: "前端资源整合"
